apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::808953420819:role/eksctl-demo-cluster-1-cluster-ServiceRole-R9QABQ7BR7MC
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::408421298729:role/eksctl-demo-cluster-1-cluster-ServiceRole-h3CqJiMvUmwP
      username: build
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::408421298729:user/kamlesh
      username: kamlesh
      groups:
        - system:masters



kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system